const express = require("express");
const router = express.Router();
const adminController = require('../controllers/adminController');
const {stillSignedInCheck, checkIfAdminRole, checkIfAdminOrSupportRole} = require("../middlewares/checkers");

router.get('/client/switchRemove/:idc',checkIfAdminOrSupportRole,adminController.getSwitchRemoveClient);
router.get('/invoice/switchRemove/:idi',checkIfAdminOrSupportRole,adminController.getSwitchRemoveInvoice);
router.get('/order/switchRemove/:ido',checkIfAdminOrSupportRole,adminController.getSwitchRemoveOrder);
router.get('/user/:id/delete',checkIfAdminRole,adminController.getDeleteUserAndAllOfObjects);
router.get('/users', checkIfAdminOrSupportRole,adminController.getAllUser);
router.get('/',checkIfAdminOrSupportRole, adminController.getAdminPanel);
router.get('/broadcast',checkIfAdminOrSupportRole, adminController.getBroadcastPage);
router.get('/database',checkIfAdminRole, adminController.getDatabasePage);
router.get('/user/:uid',checkIfAdminOrSupportRole,adminController.getUser);
router.get('/user/:uid/clients',checkIfAdminOrSupportRole,adminController.getUserClients);
router.get('/user/:uid/invoices',checkIfAdminOrSupportRole,adminController.getUserInvoices);
router.get('/user/:uid/orders',checkIfAdminOrSupportRole,adminController.getUserOrders);
router.get('/user/:uid/activities',checkIfAdminOrSupportRole,adminController.getUserActivities);
router.get('/user/:uid/block',checkIfAdminRole,adminController.getUserBlock);
router.get('/user/invoice/paid/:idi',checkIfAdminOrSupportRole,adminController.getPaid);
router.get('/user/invoice/send/:idi',checkIfAdminOrSupportRole,adminController.switchSend);
router.get('/user/offer/agreed/:idi',checkIfAdminOrSupportRole,adminController.offerAgreedGet);
router.get('/user/offer/agreed/:idi',checkIfAdminOrSupportRole,adminController.offerAgreedGet);
router.post('/user/changeNrCurrent/:pid',checkIfAdminOrSupportRole,adminController.postChangeNrCurrent);
router.get('/user/:uid/changeRole/:role',checkIfAdminRole,adminController.getChangeRole);
router.get('/user/undo/:id',checkIfAdminOrSupportRole,adminController.getUndoRemovedActivity);
router.get('/user/removePerm/:id',checkIfAdminOrSupportRole,adminController.getRemovePermanent);
router.get('/user/remove/:id',checkIfAdminOrSupportRole,adminController.getRemoveActivity);
router.post('/search',checkIfAdminOrSupportRole,adminController.adminSearchGet);
router.post('/broadcast/new',checkIfAdminRole,adminController.postCreateBroadcast);
router.get('/broadcast/remove/:id',checkIfAdminRole,adminController.getRemoveBroadcast);
router.get('/support',checkIfAdminOrSupportRole,adminController.getSupportAdmingPage);
router.get('/invoice/all/:idc',checkIfAdminOrSupportRole,adminController.getAllInvoicesOfClientAdmin);
router.get('/order/all/:idi',checkIfAdminOrSupportRole,adminController.getAllOrdersOfInvoiceAdmin);
router.get('/invoice/change/downgrade/:idi',checkIfAdminOrSupportRole,adminController.invoiceDowngradeAdminGet);
router.get('/invoice/change/upgrade/:idi',checkIfAdminOrSupportRole,adminController.invoiceUpgradeAdminGet);
router.get('/user/:idu/credits/remove',checkIfAdminRole,adminController.getRemoveCreditsToUser);
router.get('/user/:idu/credits/add',checkIfAdminRole,adminController.getAddCreditsToUser);
router.get('/edit/invoice/:idi',checkIfAdminRole,adminController.getEditInvoice);
router.post('/edit/invoice/:idi/update',checkIfAdminRole,adminController.postEditUpdateInvoice);
router.get('/edit/client/:idc',checkIfAdminRole,adminController.getEditClient);
router.post('/edit/client/:idc/update',checkIfAdminRole,adminController.postEditUpdateClient);

module.exports = router;
