const express = require("express");
const router = express.Router();
const adminController = require('../controllers/adminController');
const {stillSignedInCheck, checkIfAdminRole, checkIfAdminOrSupportRole} = require("../middlewares/checkers");
router.get('/users', checkIfAdminOrSupportRole,adminController.getAllUser);
router.get('/',checkIfAdminOrSupportRole, adminController.getAdminPanel);
router.get('/broadcast',checkIfAdminOrSupportRole, adminController.getBroadcastPage);
router.get('/database',checkIfAdminRole, adminController.getDatabasePage);
router.get('/user/:uid',checkIfAdminOrSupportRole,adminController.getUser);
router.get('/user/:uid/clients',checkIfAdminOrSupportRole,adminController.getUserClients);
router.get('/user/:uid/invoices',checkIfAdminOrSupportRole,adminController.getUserInvoices);
router.get('/user/:uid/orders',checkIfAdminOrSupportRole,adminController.getUserOrders);
router.get('/user/:uid/activities',checkIfAdminOrSupportRole,adminController.getUserActivities);
router.get('/user/:uid/block',checkIfAdminRole,adminController.getUserBlock);
router.get('/user/invoice/paid/:idi',checkIfAdminOrSupportRole,adminController.getPaid);
router.get('/user/invoice/send/:idi',checkIfAdminOrSupportRole,adminController.switchSend);
router.get('/user/offer/agreed/:idi',checkIfAdminOrSupportRole,adminController.offerAgreedGet);
router.get('/user/offer/agreed/:idi',checkIfAdminOrSupportRole,adminController.offerAgreedGet);
router.post('/user/changeNrCurrent/:pid',checkIfAdminOrSupportRole,adminController.postChangeNrCurrent);
router.get('/user/:uid/changeRole/:role',checkIfAdminRole,adminController.getChangeRole);
router.get('/user/undo/:id',checkIfAdminOrSupportRole,adminController.getUndoRemovedActivity);
router.get('/user/removePerm/:id',checkIfAdminOrSupportRole,adminController.getRemovePermanent);
router.get('/user/remove/:id',checkIfAdminOrSupportRole,adminController.getRemoveActivity);
router.post('/search',checkIfAdminOrSupportRole,adminController.adminSearchGet);
router.post('/broadcast/new',checkIfAdminRole,adminController.postCreateBroadcast);
router.get('/broadcast/remove/:id',checkIfAdminRole,adminController.getRemoveBroadcast);
router.get('/support',checkIfAdminOrSupportRole,adminController.getSupportAdmingPage);

module.exports = router;